# Generated by Django 2.0.2 on 2018-03-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('refreshed', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='saved_rates',
            field=models.ManyToManyField(to='rates.Rate'),
        ),
    ]
